#* packages
library(tidyverse)
library(parallel)
library(sf)
library(spatialsample)
library(car)
library(broom)
library(mgcv)
library(shapr)
library(ranger)
library(fixest)
library(spatialRF)
library(grf)
library(here)
library(tmap)
library(data.table)
library(gtools)